# Generated by Django 2.1.7 on 2019-04-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190327_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.RemoveField(
            model_name='class',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='students',
        ),
        migrations.RemoveField(
            model_name='courseteacher',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseteacher',
            name='teachers',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseStudent',
        ),
        migrations.DeleteModel(
            name='CourseTeacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
