# Generated by Django 3.1.1 on 2020-11-03 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('doc_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=50)),
                ('preview_link', models.CharField(max_length=280)),
                ('download_link', models.CharField(max_length=280)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
