# Generated by Django 3.1.1 on 2020-12-09 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20201209_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='class_id',
            new_name='classid',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.coursestudent'),
            preserve_default=False,
        ),
    ]
