# Generated by Django 2.1.7 on 2019-04-12 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_complete',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.CharField(default=None, max_length=280),
            preserve_default=False,
        ),
    ]
